name: dart_api
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.3

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  shelf: ^1.4.1
  shelf_cors_headers: ^0.1.5
  shelf_router: ^1.1.4
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.6
  build_web_compilers: ^4.0.6
  lints: ^2.0.0
  test: ^1.21.0
